
zuul:
  # Ignore all Eureka services except those with specific routes (below)
  ignoredServices: "*"
  routes:
    # routes any request starting "/api" to service with Eureka ID api-gateway.  Does not strip "/api" off of URL.
    api-gateway:
      path: /api/**
      stripPrefix: false
    admin-server:
      path: /admin-server/**
      stripPrefix: false
  ignoreLocalService: false

logging:
  level:
    root: INFO
