turbine:
#  clusterNameExpression: 'default'
  appConfig: PING-SERVICE,API-GATEWAY  
  aggregator: 
    clusterConfig: PING-SERVICE,API-GATEWAY
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

#logging:
#  level:
#    root: WARN
#    com.netflix.discovery: 'OFF'

eureka:
  instance:
    hostame: localhost
    leaseRenewalIntervalInSeconds: 3
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  
    healthcheck:
      enabled: true

